### ISSUE TITLE
FW 3.60

### ISSUE THREAD

**Issue by dkrmdi** [inthecatsdreams/vita-volume#1]
It does not work for me. It crashes.

**Comment by inthecatsdreams** [comment]
Works fine for me. Which version did you download? Try deleting the current version you have installed and reinstall the latest one.

**Comment by inthecatsdreams** [comment]
Do you know someone that could test it as well? I don't know anyone who has a vita, so sadly I can't test it on other units than my own.

**Comment by dkrmdi** [comment]
I was very busy. I'll let you know the result after I test them. Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dkrmdi** [comment]
Ugh. I'm a noob so I can't install it if it is not in the VPK format.

I think I don't really need this homebrew though. I was looking for something that allows to mute or change the volume using different buttons.
